---
  root: true
  extends:
    - eslint:recommended
    - plugin:vue/essential
    - standard

  env:
    browser: true

  parserOptions:
    parser: babel-eslint

  plugins:
    - vue

  rules:
    no-new: 0
    generator-star-spacing: 0
    no-debugger: 2
    comma-dangle: 0
    no-unused-vars: 1
    no-console: 0
    eqeqeq: 2
    no-else-return: 1
    no-empty-function: 1
    no-unexpected-multiline: 1
    dot-location: 1
    guard-for-in: 0
    no-invalid-this: 0
    space-before-function-paren: 0
    indent: 0
    no-eval: 2
    default-case: 2
    no-bitwise: 2
    semi: 0
    radix: 2
    max-len: [
      1,
      140
    ]
